### ISSUE TITLE
Backport to node.js version 4 LTS

### ISSUE THREAD

**Issue by 4kochi** [marcoscaceres/karma-safaritechpreview-launcher#3]
When using node.js < 4 the plugin cannot be loaded since the code uses ES2015 features

```
Error during loading "karma-safaritechpreview-launcher" plugin:
  /home/travis/build/litixsoft/karma-detect-browsers/node_modules/karma-safaritechpreview-launcher/index.js:11
const async = require('marcosc-async');
^^^^^
Use of const in strict mode.
```

So maybe you specify the engine property in the `package.json`:

```
"engines": {
  "node": ">=4"
}
```

so that the users will get a warning during `npm install`

Or you use es5 instead.

**Comment by marcoscaceres** [comment]
I'd prefer to keep using ES6. Node 6 is just around the corner and it comes with near complete ES6 support. Having said that, I don't know what the distribution of users are using older version of node 🤔.

**Comment by 4kochi** [comment]
I guess since it is a small plugin with not much code it would be helpful to support as most platforms as possible. A recent tweet from a npm employee indicates that a reasonable amount of user have node.js installed. 

But using ES6 is also fine. Just the warning would be fine so that one is aware of the restrictions before running the plugin.

**Comment by 4kochi** [comment]
https://pbs.twimg.com/media/CeLnq2uUYAABe5s.jpg:large

**Comment by marcoscaceres** [comment]
WOW! Node 4 is going up!!?!?

**Comment by 4kochi** [comment]
It is the current LTS release. That may be the reason.

**Comment by marcoscaceres** [comment]
Ok, I'll see if I can backport this then... or at least transpile it. Might take me a few days, as I'm busy on another project.

**Comment by 4kochi** [comment]
You don't have to. Node.js v4 is fine. It supports the ES2015 features you use. The engine property also include that version (>= 4)

**Comment by marcoscaceres** [comment]
I like it when I don't have to do anything :dancer:

**Comment by nickmccurdy** [comment]
It seems like there has been a regression since then that is breaking this plugin on Node 4. Here's an example failing build of a project that depends on this package: https://travis-ci.org/litixsoft/karma-detect-browsers/jobs/173932752
