### ISSUE TITLE
Regression: Syntax error breaks Node ^4.0.0 (active LTS) support

### ISSUE THREAD

**Issue by nickmccurdy** [marcoscaceres/karma-safaritechpreview-launcher#5]
An update to `marcosc-async` introduced the spread (`...`) syntax, which isn't supported in Node ^4.0.0 without the `--harmony` flag. This causes Node 4 to break with this package. I almost created an issue on `marcosc-async`, but I thought it would be less confusing here since this package has Node >=4 in `engines` while `marcosc-async` doesn't define `engines`.

Example failing build: https://travis-ci.org/litixsoft/karma-detect-browsers/jobs/173932752

## Possible Solutions
- Set `engines` to Node >=5
- Publish a new release of `marcosc-async` that's compatible with Node 4 syntax and depend on that in this package (ideal solution in my opinion, since it's still an active LTS version)

**Comment by marcoscaceres** [comment]
@nickmccurdy, thanks for reporting, just fixed marcosc-async to work with Node 4.0 and above. Added engines member to the package, as suggested.

**Comment by marcoscaceres** [comment]
Should be fixed now.... please reopen if still broken.

**Comment by nickmccurdy** [comment]
Thanks, this fixes warnings in `karma-detect-browsers`.
