### ISSUE TITLE
Requires user intervention on Safari 12 on macOS Mojave

### ISSUE THREAD

**Issue by gkatsev** [marcoscaceres/karma-safaritechpreview-launcher#7]
This is a clone of https://github.com/karma-runner/karma-safari-launcher/issues/29. It looks like a file permission issue. The current workaround is the following change:
```js
// const staticHtmlPath = self._tempDir + '/redirect.html';
const staticHtmlPath = path.join(process.env.HOME, 'Library/Containers/com.apple.SafariTechnologyPreview/Data/redirect.html');
```

**Comment by marcoscaceres** [comment]
hmmm... should I just update to use the above then?

**Comment by gkatsev** [comment]
Maybe. I haven't done extensive testing with it, particularly, don't know how well it works with older versions of macOS.

**Comment by marcoscaceres** [comment]
Ok, what I can do is ship a major “BREAKING CHANGE” release. That will give any depent folks a heads up that it’s for Majove onwards. People can the choose to sit on the old version or upgrade if needed.
